<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Clay.Csharp\Clay.Csharp.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Raylib-cs" Version="8.0.0" />
    </ItemGroup>

</Project>
